2023-12-15 00:53:23,447 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2023-12-15 00:53:23,453 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2023-12-15 00:53:23,457 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "sacharjeeofficial@gmail.com", --configuration: "default", --format: "value(name)", PROJECT_ID_OR_NUMBER: "mathgaps-56d5a"]
2023-12-15 00:53:23,511 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-12-15 00:53:23,519 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/mathgaps-56d5a?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10785ecd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-12-15 00:53:23,519 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/mathgaps-56d5a?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/mathgaps-56d5a?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10785ecd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
